### ISSUE TITLE
ImportError for module 'gribapi'

### ISSUE THREAD

**Issue by laugri** [erget/PythonicGRIB#1]
Hi there,

`import pyth_grib` raises `ImportError: No module named 'gribapi'` and I can't figure out where to find and install this `gribapi` package.
`pip install gribapi` does not yield any result and I didn't find anything on pypi either.

I guess it refers to the [ecmwf grib api](https://software.ecmwf.int/wiki/display/GRIB/Python+package+gribapi) but I can't find any instruction on how to install it.

Any help would be very appreciated ! :)

Thanks a lot !

**Comment by erget** [comment]
You'll need to [install the GRIB API in its entirety](https://software.ecmwf.int/wiki/display/GRIB/Releases) - the corresponding Python package provided by ECMWF is part of the library, so it's not independent. ECMWF provides instructions for installing from source, but there might be a package for your distro. HTH!

**Comment by cglevican** [comment]
I already install the GRIB API correctly but I have the same error: ImportError: No module named 'gribapi'

I include -DENABLE_PYTHON=ON:
cmake ../grib_api-1.27.0-Source -DCMAKE_INSTALL_PREFIX=/home/constanza/Documentos -DENABLE_PYTHON=ON

**Comment by erget** [comment]
This code has now been incorporated into [ecCodes](https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home). GRIB API is no longer supported, which is probably why this doesn't work. Sorry for the confusion; I'm taking this repository offline to avoid future mixups. Installing ecCodes with Python support will give you the full functionality this package used to contain.
